name: build

on: push

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node: [12, 14, 16, 17]
        os: ['bullseye', 'alpine']
    env:
      default_node: 17
      default_os: bullseye
      pnpm_patch: 6.24.4
      pnpm_minor: 6.24
      pnpm_major: 6
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build images
      run: 'docker build --build-arg base=$node-$os -t gplane/pnpm:$pnpm_patch-$node-$os -t gplane/pnpm:$pnpm_minor-$node-$os -t gplane/pnpm:$pnpm_major-$node-$os .'
      env:
        node: ${{ matrix.node }}
        os: ${{ matrix.os }}
    - name: Build images with default OS
      if: ${{ matrix.os == env.default_os }}
      run: 'docker build --build-arg base=$node-$default_os -t gplane/pnpm:$pnpm_patch-$node -t gplane/pnpm:$pnpm_minor-$node -t gplane/pnpm:$pnpm_major-$node .'
      env:
        node: ${{ matrix.node }}
    - name: Build images with default Node.js
      if: ${{ matrix.node == env.default_node && matrix.os == env.default_os }}
      run: 'docker build --build-arg base=$default_node-$default_os -t gplane/pnpm:$pnpm_patch -t gplane/pnpm:$pnpm_minor -t gplane/pnpm:$pnpm_major -t gplane/pnpm .'
    - name: Test images
      run: |
        docker run gplane/pnpm:$pnpm_patch-$node-$os -v
        docker run gplane/pnpm:$pnpm_minor-$node-$os -v
        docker run gplane/pnpm:$pnpm_major-$node-$os -v
      env:
        node: ${{ matrix.node }}
        os: ${{ matrix.os }}
    - name: Test images
      if: ${{ matrix.os == env.default_os }}
      run: |
        docker run gplane/pnpm:$pnpm_patch-$node -v
        docker run gplane/pnpm:$pnpm_minor-$node -v
        docker run gplane/pnpm:$pnpm_major-$node -v
      env:
        node: ${{ matrix.node }}
    - name: Test images
      if: ${{ matrix.node == env.default_node && matrix.os == env.default_os }}
      run: |
        docker run gplane/pnpm:$pnpm_patch -v
        docker run gplane/pnpm:$pnpm_minor -v
        docker run gplane/pnpm:$pnpm_major -v
        docker run gplane/pnpm -v
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish images
      run: |
        docker push gplane/pnpm:$pnpm_patch-$node-$os
        docker push gplane/pnpm:$pnpm_minor-$node-$os
        docker push gplane/pnpm:$pnpm_major-$node-$os
      env:
        node: ${{ matrix.node }}
        os: ${{ matrix.os }}
    - name: Publish images
      if: ${{ matrix.os == env.default_os }}
      run: |
        docker push gplane/pnpm:$pnpm_patch-$node
        docker push gplane/pnpm:$pnpm_minor-$node
        docker push gplane/pnpm:$pnpm_major-$node
      env:
        node: ${{ matrix.node }}
    - name: Publish images
      if: ${{ matrix.node == env.default_node && matrix.os == env.default_os }}
      run: |
        docker push gplane/pnpm:$pnpm_patch
        docker push gplane/pnpm:$pnpm_minor
        docker push gplane/pnpm:$pnpm_major
        docker push gplane/pnpm
